version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}
    networks:
      - blog_networks

  blog:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - DB_HOST=mysql
        - DB_PORT=3306
        - DB_NAME=${DB_NAME}
        - DB_USER=root
        - DB_PASSWD=${DB_PASSWD}
    tty: true
    networks:
      - blog_networks
    restart: always
    depends_on:
      - mysql
    environment:
      - PORT=${WEB_PORT-8000}
    ports:
      - "${WEB_PORT-8000}:${WEB_PORT-8000}"

    

networks:
  blog_networks:


