# Generated by Django 4.2.5 on 2023-09-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='count',
            field=models.IntegerField(default=1, verbose_name='分类数目'),
        ),
        migrations.AddField(
            model_name='tag',
            name='count',
            field=models.IntegerField(default=1, verbose_name='标签数目'),
        ),
    ]
